"""order_state_machine.py — Phase 6 (6.1): explicit order lifecycle."""
from __future__ import annotations
STATES=["SIGNAL_CREATED","DECISION_APPROVED","ENTRY_SUBMITTED","ENTRY_PARTIAL","ENTRY_FILLED",
"PROTECTION_PENDING","PROTECTED","EXIT_SUBMITTED","CLOSED","REJECTED","RECONCILIATION_REQUIRED"]
_T={"SIGNAL_CREATED":{"DECISION_APPROVED","REJECTED"},"DECISION_APPROVED":{"ENTRY_SUBMITTED","REJECTED"},
"ENTRY_SUBMITTED":{"ENTRY_PARTIAL","ENTRY_FILLED","REJECTED","RECONCILIATION_REQUIRED"},
"ENTRY_PARTIAL":{"ENTRY_FILLED","PROTECTION_PENDING","RECONCILIATION_REQUIRED"},
"ENTRY_FILLED":{"PROTECTION_PENDING","RECONCILIATION_REQUIRED"},
"PROTECTION_PENDING":{"PROTECTED","RECONCILIATION_REQUIRED"},"PROTECTED":{"EXIT_SUBMITTED","RECONCILIATION_REQUIRED"},
"EXIT_SUBMITTED":{"CLOSED","RECONCILIATION_REQUIRED"},"CLOSED":set(),"REJECTED":set(),
"RECONCILIATION_REQUIRED":{"PROTECTED","CLOSED","REJECTED"}}
class InvalidTransition(RuntimeError): pass
def can_transition(frm,to): return to in _T.get(frm,set())
def transition(frm,to):
    if not can_transition(frm,to): raise InvalidTransition(f"{frm} -> {to} not allowed")
    return to
def is_terminal(s): return s in ("CLOSED","REJECTED")
