"""ports.py — Phase 5: engine interfaces. Adapters implement these -> one engine everywhere."""
from __future__ import annotations
from typing import Protocol,List,runtime_checkable
@runtime_checkable
class MarketDataPort(Protocol):
    def get_snapshot(self,symbol,security_id): ...
    def universe(self)->List[dict]: ...
@runtime_checkable
class BrokerPort(Protocol):
    def place(self,intent)->dict: ...
    def cancel(self,order_id)->dict: ...
    def positions(self)->List[dict]: ...
    def orders(self)->List[dict]: ...
@runtime_checkable
class ClockPort(Protocol):
    def now(self): ...
    def is_market_open(self)->bool: ...
@runtime_checkable
class StateRepository(Protocol):
    def save_position(self,pos)->None: ...
    def load_positions(self)->List[dict]: ...
    def record_event(self,event:dict)->None: ...
@runtime_checkable
class EventSink(Protocol):
    def emit(self,event,**fields)->None: ...
