"""reason_codes.py — Phase 1: canonical status + reason-code vocabulary. Pure stdlib."""
from __future__ import annotations
from typing import Final
class RRStatus:
    DISABLED:Final="DISABLED"; MODEL_NOT_FOUND:Final="MODEL_NOT_FOUND"; META_NOT_FOUND:Final="META_NOT_FOUND"
    LIGHTGBM_NOT_AVAILABLE:Final="LIGHTGBM_NOT_AVAILABLE"; SCHEMA_MISMATCH:Final="SCHEMA_MISMATCH"
    INSUFFICIENT_BARS:Final="INSUFFICIENT_BARS"; INVALID_FEATURE:Final="INVALID_FEATURE"
    PREDICTION_ERROR:Final="PREDICTION_ERROR"; LOW_CONFIDENCE:Final="LOW_CONFIDENCE"
    OUT_OF_RANGE:Final="OUT_OF_RANGE"; ACCEPTED:Final="ACCEPTED"; FALLBACK_USED:Final="FALLBACK_USED"
RR_STATUSES:Final=frozenset({RRStatus.DISABLED,RRStatus.MODEL_NOT_FOUND,RRStatus.META_NOT_FOUND,
RRStatus.LIGHTGBM_NOT_AVAILABLE,RRStatus.SCHEMA_MISMATCH,RRStatus.INSUFFICIENT_BARS,RRStatus.INVALID_FEATURE,
RRStatus.PREDICTION_ERROR,RRStatus.LOW_CONFIDENCE,RRStatus.OUT_OF_RANGE,RRStatus.ACCEPTED,RRStatus.FALLBACK_USED})
RR_SUCCESS:Final=frozenset({RRStatus.ACCEPTED}); RR_FALLBACK:Final=RR_STATUSES-RR_SUCCESS-{RRStatus.DISABLED}
class Reason:
    RR_DISABLED:Final="RR_DISABLED"; RR_SCHEMA_VALID:Final="RR_SCHEMA_VALID"; RR_SCHEMA_INVALID:Final="RR_SCHEMA_INVALID"
    RR_CONFIDENCE_PASSED:Final="RR_CONFIDENCE_PASSED"; RR_CONFIDENCE_LOW:Final="RR_CONFIDENCE_LOW"
    RR_ACCEPTED:Final="RR_ACCEPTED"; RR_FALLBACK:Final="RR_FALLBACK"; RR_INSUFFICIENT_BARS:Final="RR_INSUFFICIENT_BARS"
    EXIT_STRUCTURE_USED:Final="EXIT_STRUCTURE_USED"; EXIT_STRATEGY_USED:Final="EXIT_STRATEGY_USED"
    EXIT_ATR_FALLBACK:Final="EXIT_ATR_FALLBACK"; EXIT_RR_USED:Final="EXIT_RR_USED"
    KRONOS_OFF:Final="KRONOS_OFF"; KRONOS_NO_VIEW:Final="KRONOS_NO_VIEW"; KRONOS_CONSTRAINT_APPLIED:Final="KRONOS_CONSTRAINT_APPLIED"
    KRONOS_SKIPPED_RR_OWNS_EXIT:Final="KRONOS_SKIPPED_RR_OWNS_EXIT"; KRONOS_VETO:Final="KRONOS_VETO"
    DIRECTION_GATE_PASSED:Final="DIRECTION_GATE_PASSED"; DIRECTION_GATE_FAILED:Final="DIRECTION_GATE_FAILED"
    SL_WRONG_SIDE:Final="SL_WRONG_SIDE"; TGT_WRONG_SIDE:Final="TGT_WRONG_SIDE"
    SL_DISTANCE_OUT_OF_LIMITS:Final="SL_DISTANCE_OUT_OF_LIMITS"; RR_BELOW_MIN:Final="RR_BELOW_MIN"
    NON_FINITE_VALUE:Final="NON_FINITE_VALUE"; QTY_ZERO:Final="QTY_ZERO"; MAX_RISK_EXCEEDED:Final="MAX_RISK_EXCEEDED"
    PLAN_VALID:Final="PLAN_VALID"; ALLOC_SHADOW:Final="ALLOC_SHADOW"; ALLOC_ACTIVE:Final="ALLOC_ACTIVE"
class Event:
    SIGNAL_CREATED:Final="signal_created"; SIGNAL_REJECTED:Final="signal_rejected"; MODEL_PREDICTION:Final="model_prediction"
    EXIT_RESOLVED:Final="exit_resolved"; ORDER_SUBMITTED:Final="order_submitted"; ORDER_REJECTED:Final="order_rejected"
    POSITION_CHANGED:Final="position_changed"; FALLBACK_INVOKED:Final="fallback_invoked"; STATE_RESTORED:Final="state_restored"
LOG_EVENTS:Final=frozenset({Event.SIGNAL_CREATED,Event.SIGNAL_REJECTED,Event.MODEL_PREDICTION,Event.EXIT_RESOLVED,
Event.ORDER_SUBMITTED,Event.ORDER_REJECTED,Event.POSITION_CHANGED,Event.FALLBACK_INVOKED,Event.STATE_RESTORED})
class ExitSource:
    STRUCTURE:Final="structure"; STRATEGY:Final="strategy"; ATR:Final="atr"; RR_MODEL:Final="rr_model"; KRONOS:Final="kronos"
EXIT_SOURCES:Final=frozenset({ExitSource.STRUCTURE,ExitSource.STRATEGY,ExitSource.ATR,ExitSource.RR_MODEL,ExitSource.KRONOS})
def is_valid_rr_status(s): return s in RR_STATUSES
def is_fallback_status(s): return s in RR_FALLBACK
